spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to ABCBank accounts related local APIs"
  contactDetails:
    name: "Contact us at 1234567890"
    email: "t8P8o@example.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345